### ISSUE TITLE
 proxmox-kernel-6.5.11-7-pve-signed conflicts with proxmox-kernel-6.5.11-7-pve

### ISSUE THREAD

**Issue by xws6** [roforest/Actions-pve-kernel#2]
dpkg: regarding proxmox-kernel-6.5.11-7-pve_6.5.11-7_amd64.deb containing proxmox-kernel-6.5.11-7-pve:
 proxmox-kernel-6.5.11-7-pve-signed conflicts with proxmox-kernel-6.5.11-7-pve
  proxmox-kernel-6.5.11-7-pve (version 6.5.11-7) is to be installed.

dpkg: error processing archive proxmox-kernel-6.5.11-7-pve_6.5.11-7_amd64.deb (--install):
 conflicting packages - not installing proxmox-kernel-6.5.11-7-pve
Preparing to unpack proxmox-kernel-6.5.11-7-pve-signed-template_6.5.11-7_amd64.deb ...
Unpacking proxmox-kernel-6.5.11-7-pve-signed-template (6.5.11-7) over (6.5.11-7) ...
Preparing to unpack proxmox-kernel-6.5_6.5.11-7_all.deb ...
Unpacking proxmox-kernel-6.5 (6.5.11-7) over (6.5.11-7) ...
Preparing to unpack proxmox-kernel-libc-dev_6.5.11-7_amd64.deb ...
Unpacking proxmox-kernel-libc-dev (6.5.11-7) over (6.5.11-7) ...
dpkg: dependency problems prevent configuration of linux-tools-6.5:
 linux-tools-6.5 depends on libpfm4 (>= 4.9); however:
  Package libpfm4 is not installed.

dpkg: error processing package linux-tools-6.5 (--install):
 dependency problems - leaving unconfigured
dpkg: dependency problems prevent configuration of linux-tools-6.5-dbgsym:
 linux-tools-6.5-dbgsym depends on linux-tools-6.5 (= 6.5.11-7); however:
  Package linux-tools-6.5 is not configured yet.

dpkg: error processing package linux-tools-6.5-dbgsym (--install):
 dependency problems - leaving unconfigured

**Comment by roforest** [comment]
If you don't need Secure Boot, the unsigned kernel can be installed by
`apt install proxmox-kernel-6.5.11-7-pve`
